---
sudo: required
dist: trusty
language: rust
cache:
  cargo: true
  directories:
    - $HOME/.rustup

addons:
  apt:
    packages:
      - texinfo
      - libgif-dev
      - libxmp-dev
      - libgnutls28-dev
  homebrew:
    packages:
    - gnutls
    - texinfo

# Run rustfmt first.
stages:
  - rustfmt
  - clippy
  - test

jobs:
  allow_failures:
    - script: make clippy
    - os: osx
  include:
    - stage: rustfmt
      os: linux  # No need to run this everywhere
      before_script:
        - travis_wait rustup install $(cat rust-toolchain)
        - travis_wait rustup component add rustfmt-preview
        - ./autogen.sh && ./configure --without-makeinfo --with-x=no --with-ns=no --without-gconf --without-gsettings
      script: ./.travis-format.sh
    - stage: clippy
      os: linux  # No need to run this everywhere
      before_script:
        - sudo apt install -y libgtk-3-dev
        - travis_wait rustup component add clippy-preview
        - ./autogen.sh && ./configure --without-makeinfo
      script:
        - make clippy
    - &FULL_TEST
      stage: test
      env:
        # Ensure that we build without warnings.
        - CARGO_FLAGS="--features 'strict'"
        - RUST_BACKTRACE=1
      os: linux
      before_script:
        - sudo apt install -y libgtk-3-dev
        - travis_wait rustup install $(cat rust-toolchain)
      script:
        # The -Wno-error allows MacOS code deprecation warnings to remain warnings.
        - ./autogen.sh && RUSTFLAGS="-Dwarnings" WERROR_CFLAGS='-Werror -Wno-error=deprecated-declarations' ./configure
        - make -j 3 && echo '==> Running tests' && make check
    -
      <<: *FULL_TEST
      os: osx
      env:
        - PATH="/usr/local/opt/texinfo/bin:$PATH"
      before_script:
        - travis_wait rustup install $(cat rust-toolchain)
    - &NO_WINDOW_SYSTEM_TEST
      stage: test
      os: linux
      env:
        # Ensure that we build without warnings.
        - CARGO_FLAGS="--features 'strict'"
        - TRAVIS_WITH_NO_WINDOW_SYSTEM=1  # So we can tell them apart
        - RUST_BACKTRACE=1
      before_script:
        - travis_wait rustup install $(cat rust-toolchain)
      script:
        - ./autogen.sh && RUSTFLAGS="-Dwarnings" WERROR_CFLAGS='-Werror  -Wno-error=deprecated-declarations' ./configure --without-makeinfo --with-x=no --with-ns=no --without-gconf --without-gsettings
        - make -j 3 && echo '==> Running nowindow tests' && make check
    -
      <<: *NO_WINDOW_SYSTEM_TEST
      os: osx
      before_script:
        - travis_wait rustup install $(cat rust-toolchain)

notifications:
  fast_finish: true
  email: false

matrix:
  fast_finish: true
