version: '2'

services:
  lambda:
    build:
      context: .
      dockerfile: docker/ubuntu/Dockerfile
    image: lambda-build:latest
    working_dir: ${PWD}
    tty: true
    # Unfortunately dumping doesn't work without this
    privileged: true
    volumes:
      - .:${PWD}
